[2025-05-12T08:00:30.608+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation_pipeline.transform_data manual__2025-05-12T08:00:28.965047+00:00 [queued]>
[2025-05-12T08:00:30.619+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation_pipeline.transform_data manual__2025-05-12T08:00:28.965047+00:00 [queued]>
[2025-05-12T08:00:30.620+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-12T08:00:30.639+0000] {taskinstance.py:1380} INFO - Executing <Task(DockerOperator): transform_data> on 2025-05-12 08:00:28.965047+00:00
[2025-05-12T08:00:30.646+0000] {standard_task_runner.py:57} INFO - Started process 68 to run task
[2025-05-12T08:00:30.650+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_transformation_pipeline', 'transform_data', 'manual__2025-05-12T08:00:28.965047+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmpf1z8su34']
[2025-05-12T08:00:30.652+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask transform_data
[2025-05-12T08:00:30.671+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task transform_data (invalid interpolation syntax in 'dag_id={{ ti.dag_id }}/run_id={{ ti.run_id }}/task_id={{ ti.task_id }}/{% if ti.map_index >= 0 %}map_index={{ ti.map_index }}/{% endif %}attempt={{ try_number }}.log' at position 72; 68)
[2025-05-12T08:00:30.705+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-12T08:00:30.726+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
